apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: nginx-demo
spec:
  selector:
    app: nginx-demo
  ports:
  - protocol: TCP
    port: 80          # port di service
    targetPort: 80    # port di container
    nodePort: 30080   # port yang bisa diakses dari luar node
  type: NodePort
